---
title: Générer des données synthétiques
order: 5
---

```{r}
setwd("/Users/julienjamme/Documents/Code/formation_protection_donnees/pratique/fiches")
```

```{r}
#| echo: false
library(readr)
library(purrr)
library(dplyr)
library(synthpop)
```

## Importons les données

```{r}
source("../R/fun_import_data.R")
lfs_2023 <- import_lfs()
```


```{r}
head(lfs_2023)
```

Pour plus d'informations sur les données, on pourra se reporter à la fiche 
["Présentation des données"](description-data.html).  


## Préparation des données

```{r}
lfs_orig <- lfs_2023 |> 
    select(-starts_with("HH")) |>
    select(-ARR) |>
    mutate(across(-AGE, as.character))
```

## Ordre des variables

```{r}
seq1 <- lfs_orig |> select(where(is.character)) |> 
    unique() |> 
    tidyr::pivot_longer(everything(), names_to = "var", values_to = "mod") |>
    unique() |>
    count(var) |>
    arrange(n) |>
    pull(var)
```

## Synthétiser
```{r}
lfs_syn <- synthpop::syn(lfs_orig, method = "cart", visit.sequence = seq1)
```

## Risque / Utilité
