website:
  title: "La protection des données statistiques publiques"
  description: |
    "Formation en ligne sur la protection des données statistiques contre 
    les risques de divulgation à destination des producteurs de statistiques publiques."
  page-footer:
    left: "© 2025 - Insee"
    right: "Site réalisé avec Quarto"
  navbar:
    right:
      - href: index.qmd
        text: "Accueil"
      - href: theorie/index.qmd
        text: "Un peu de théorie"
      - href: pratique/index.qmd
        text: "En pratique"
      - href: ressources/index.qmd
        text: "Ressources"
      - href: glossaire/index.qmd
        text: "Glossaire"
      - href: about.qmd
        text: "À propos"
  sidebar:
    - title: "Un peu de théorie"
      style: "docked"
      contents:
        - theorie/supports/arbitrer-risque-utilite.qmd
        - theorie/supports/methodes-suppressives.qmd
        - theorie/supports/methodes-perturbatrices.qmd
        - theorie/supports/mesurer-utilite.qmd
        - theorie/supports/confidentialite-differentielle.qmd
    - title: "En pratique"
      style: "docked"
      contents:
        - pratique/fiches/description-data.qmd
        - pratique/fiches/mesurer-risque.qmd
        - pratique/fiches/mesurer-utilite.qmd
        - pratique/fiches/suppressif.qmd
        - pratique/fiches/proteger-tableaux-suppressif.qmd
        - pratique/fiches/proteger-tableaux-cellkey.qmd
        - pratique/fiches/perturbatif.qmd
        - pratique/fiches/proteger-micro-agregation.qmd
        - pratique/fiches/proteger-micro-pram.qmd
        - pratique/fiches/proteger-micro-swapping.qmd
        - pratique/fiches/generer-synth.qmd
        - pratique/fiches/confidentialite-differentielle.qmd
        - pratique/fiches/arbitrage.qmd
        - pratique/fiches/analyse-automatique.qmd
        - pratique/fiches/analyse-demande.qmd
        - pratique/fiches/sujets-avances.qmd

lang: fr