project:
  type: website

execute:
  freeze: auto

author: "Insee, Département des Méthodes Statistiques"

website:
  site-url: "https://inseefrlab.github.io/formation_protection_donnees"
  
format:
  html:
    theme: 
      light: [cosmo, styles/custom-light.scss]
      dark: [cosmo, styles/custom-dark.scss]
    toc: true
    code-fold: true
    code-tools: true
    code-link: true
    reference-location: margin
    citation-location: margin
    cap-location: bottom
    bibliography: references-SDC.bib

babelquarto:
  mainlanguage: 'fr'
  languages: ['en']
  # Emplacement du bouton de bascule : 'navbar' (défaut pour website) ou 'sidebar'
  languagelinks: navbar
  languagecodes:
  - name: fr
    text: "🇫🇷 Français"
  - name: en
    text: "🇬🇧 English"


lang: fr
